### ISSUE TITLE
Utterly Useless Project

### ISSUE THREAD

**Issue by abhishek-jaisingh** [AmbarZaidi/CS103-project#2]
This project serves no purpose and is an utter wastage of time, skill and human resource. Scrape it immediately!
![1084626-homer-simpson](https://user-images.githubusercontent.com/10446685/37867334-a2c5e00e-2fbc-11e8-830b-bd23bc5ddd2a.jpg)

**Comment by AmbarZaidi** [comment]
Student_Result_Processing_System, as a software product works very well. In its present form, it is perfectly capable of saving time as well as human resource.
